/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.vinodseb.framework

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {

    @Test
    fun `dummy test`() = assertTrue {
        true
    }
}
