/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.vinodseb.framework

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.testing.*
import kotlin.test.Test
import kotlin.test.assertEquals

class ApplicationTest {
    @Test
    fun `test endpoint should return success`() = testApplication {
        client.get("/test").let {
            assertEquals(HttpStatusCode.OK, it.status)
            assertEquals("{\n" +
                    "  \"title\": \"success\",\n" +
                    "  \"header\": {},\n" +
                    "  \"banner\": {},\n" +
                    "  \"main\": [],\n" +
                    "  \"sidebar\": []\n" +
                    "}", it.bodyAsText())
        }
    }
}
