name: Framework Renderer
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'framework.app/framework.renderer/**'
      - 'framework.app/build.gradle.kts'
      - 'build.gradle.kts'
      - 'framework.lib/framework.utilities/**'
      - 'framework.lib/build.gradle.kts'
      - 'buildSrc/**'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew :framework.app:framework.renderer:build
